### ISSUE TITLE
Authentication timeout using php-saml-sp causes confusing error message

### ISSUE THREAD

**Issue by jornane** [eduvpn/vpn-user-portal#123]
Assuming SAML authentication using php-saml-sp.

When the authentication at the IdP takes a long time, the session at the SP times out as is expected. This seems to happen in a matter of minutes.

When a user attempts to present a SAML assertion after the timeout has expired, the following error is displayed to the user.

	key "_fkooman_saml_sp_auth_idp" not found in session

This is an internal error that is displayed to the user. The error should be human readable, stating that the authentication has timed out, with a button to allow the user to try again.

**Comment by fkooman** [comment]
This did not seem to be a timeout, but a lost session due to browser settings/extensions.

**Comment by fkooman** [comment]
However, a similar problem may occur when the SAML assertion as generated by the IdP already expired before reaching the SP. Not sure if we handle that gracefully...
