### ISSUE TITLE
In stats: Show maximum amount users per profile

### ISSUE THREAD

**Issue by efef** [eduvpn/vpn-user-portal#133]
The current stats show the maximum concurrent amount of users, but it doesn't show the technical limit.
<img width="861" alt="Screenshot 2019-06-19 at 11 30 33" src="https://user-images.githubusercontent.com/3393474/59754066-ad75e080-9285-11e9-8494-7d0384be3320.png">

It would be preferred to show the maximum amount of concurrent users that can use a specific profile. Basically calculate the amount of IPaddresses per profile minus the amount of daemons times 3 (netwerk/broadcast/router).

**Comment by fkooman** [comment]
will be in 2.0.6
