### ISSUE TITLE
traffic stats rounding error

### ISSUE THREAD

**Issue by fkooman** [eduvpn/vpn-user-portal#134]
it seems if > 1TiB is transferred the stats diagram shows it as 1 TiB instead of something like 1.6TiB.

**Comment by sveeke** [comment]
Pics or it didn't happen:

![image](https://user-images.githubusercontent.com/12334213/60265254-d6752180-98d4-11e9-8925-8f951abbf7ec.png)

**Comment by fkooman** [comment]
![Screenshot from 2019-06-27 16-24-25](https://user-images.githubusercontent.com/616885/60270078-53fe5900-98f8-11e9-84b4-1f1580f12b6a.png)

Something like this?

**Comment by sveeke** [comment]
You already fixed it? That's fast :).
