### ISSUE TITLE
unable to upgrade to "2019042501", not all required migrations are available

### ISSUE THREAD

**Issue by 314220079** [eduvpn/vpn-user-portal#140]
SqliteMigrate error.help please!

**Comment by fkooman** [comment]
Did you install the VPN server according to https://github.com/eduvpn/documentation/blob/v2/README.md#deployment?

**Comment by 314220079** [comment]
according to  https://github.com/eduvpn/documentation/blob/master/DEVELOPMENT_SETUP.md
error info: "unable to upgrade to "2019042501", not all required migrations are available" . dir"schema/2019042501.schema" has change 0777
What should I do?help

**Comment by fkooman** [comment]
If you really want to setup the development environment, I recommend setting up the one for "v2", i.e. follow https://github.com/eduvpn/documentation/blob/v2/DEVELOPMENT_SETUP.md
