### ISSUE TITLE
Provide links to apps from start page

### ISSUE THREAD

**Issue by jornane** [eduvpn/vpn-user-portal#146]
Currently, the startpage looks like this:
![eduVPN portal](https://user-images.githubusercontent.com/767872/63349372-8f972b80-c35b-11e9-811b-b22715cb0a5d.png)
This page instructs the user to generate and use an OpenVPN configuration file. For many users, this is not the preferred way of using eduVPN, and it may cause littering of eduVPN credentials in the users' home directory (.ovpn file not being deleted).

It would be better if the start page would list the apps that the user can use to connect to eduVPN, and hide the OpenVPN generating under another menu item. That way, users that need OpenVPN configuration files can still get them, but less advanced users are not "tricked" into using an OpenVPN configuration file.

**Comment by fkooman** [comment]
A better place to do this would be in the eduVPN theme/template: https://github.com/eduvpn/vpn-portal-artwork

**Comment by fkooman** [comment]
For example:

![Screenshot from 2019-08-20 15-43-03](https://user-images.githubusercontent.com/616885/63352381-4f3aac00-c361-11e9-92d5-d18bebf32a74.png)

**Comment by jornane** [comment]
In the illustration it is still not clear that the Download button is not the recommended course of action. It would be better to have direct download links on the start page, and move the Download button to another page, as stated.

**Comment by fkooman** [comment]
![image](https://user-images.githubusercontent.com/616885/63360795-510b6c00-c36f-11e9-81b5-c2b003a06fd5.png)

And... 

![image](https://user-images.githubusercontent.com/616885/63360837-5ec0f180-c36f-11e9-9414-fa39ec2870f9.png)

Tadaa!

**Comment by fkooman** [comment]
The exact wording of the message in the green bar is open for discussion of course! It doesn't seem to be the best.

> Please use the official eduVPN applications. Download them [[here]]

Any suggestions welcome. 

It may not be ideal to change user facing stuff too much during the 2.x release.

**Comment by jornane** [comment]
> Any suggestions welcome.

Suggestion:

    Download the eduVPN app here:

    <Windows> <Mac> <iOS> <Android> <Linux>

Maybe with outline icons, Windows logo, laptop with Apple logo, phone with Apple logo, Android, Penguin.

> It may not be ideal to change user facing stuff too much during the 2.x release.

I think it's okay with this change, because it will reduce confusion among users.

**Comment by fkooman** [comment]
Had to also implement translation files in theme packages, but the initial attempt is here :-) 

![image](https://user-images.githubusercontent.com/616885/63378888-71e5b880-c393-11e9-887c-91ce8fb4f461.png)

**Comment by jornane** [comment]
We're getting somewhere! I'd recommend moving the form under "Andere apparaten…" to the "Certificaten" tab, and renaming "Nieuw" to "Apps".

**Comment by fkooman** [comment]
> I'd recommend moving the form under "Andere apparaten…" to the "Certificaten" tab

This could be useful not just for eduVPN, but also for LC and even the 'unbranded' installation, so no need to put in the theme then. It is not currently possibly to change the routing (e.g. after form submit) from a theme... and also doesn't seem like a good idea :)

> and renaming "Nieuw" to "Apps".

This could be renamed to "Home" perhaps. It could contain some standard "Welcome!" text or similar. This is the page that is then overriden by the eduVPN theme (and LC theme) to directly point to the apps!

@efef also proposed renaming "Certificates" to "OpenVPN" or something, but maybe "Advanced" is better instead...

Now, we only have to decide if this is okay to do during 2.x...

**Comment by fkooman** [comment]
> @efef also proposed renaming "Certificates" to "OpenVPN" or something, but maybe "Advanced" is better instead...

Or back to "Config" which is what it used to be years ago ;-)

**Comment by jornane** [comment]
> @efef also proposed renaming "Certificates" to "OpenVPN" or something, but maybe "Advanced" is better instead...

I think "openVPN" is best; you'd click it if you want to use a generic OpenVPN client.

> This could be renamed to "Home" perhaps. It could contain some standard "Welcome!" text or similar. This is the page that is then overriden by the eduVPN theme (and LC theme) to directly point to the apps!

I think "Apps" is best; you download the apps from there.

**Comment by fkooman** [comment]
![image](https://user-images.githubusercontent.com/616885/65273540-aaf38300-db21-11e9-8464-e3f2245dd485.png)

**Comment by fkooman** [comment]
I mean, the logo's are not ideal, would be nice to have something better, but I think we're getting somewhere... :)

**Comment by fkooman** [comment]
Merged to v2 branch.
