### ISSUE TITLE
Disable VPN configuration download

### ISSUE THREAD

**Issue by tomhouweling1987** [eduvpn/vpn-user-portal#147]
Is it possible to disable the download for ovpn files? So we can force users only to use the Eduvpn/Letsconnect client.

**Comment by fkooman** [comment]
Currently not, unless you override the template/theme, then you can at least hide it.

https://github.com/eduvpn/documentation/blob/v2/CUSTOM_BRANDING.md

You can copy the vpnPortalNew.php template and remove the section for creating a new configuration there.

**Comment by fkooman** [comment]
https://github.com/eduvpn/vpn-user-portal/commit/a6c4a3bdddbbedf27e7196c13e37029e1088ce3c

**Comment by fkooman** [comment]
implemented for eduVPN/Let's Connect! version 3, release later this year.
