### ISSUE TITLE
"Normalize" LDAP user ID

### ISSUE THREAD

**Issue by gvde** [eduvpn/vpn-user-portal#151]
I have just noticed that one user appeared twice in the users list. We authenticate against LDAP. Looking into the db.sqlite database I have noticed that one of the user_ids had a trailing space, the other didn't. For LDAP leading or trailing white space doesn't make a difference, thus it's always the same LDAP account. But for eduvpn each different combination of white space at the beginning or end makes a different user_id.

I think leading and trailing white spaces should be removed from the user_id.

**Comment by fkooman** [comment]
Oops. Nice catch. Is the same true for passwords?

**Comment by fkooman** [comment]
I wonder if I should move this `trim` to the LDAP backend, or use `trim` for all user/pass authentication backends...

**Comment by fkooman** [comment]
I guess there is no good reason to allow whitespaces before/after usernames, so probably best to strip it everywhere...

**Comment by gvde** [comment]
I agree: user names should not have leading or trailing white spaces. I don't know any system where it is allowed.

Even whitespace in the middle are usually not allowed, but I guess as you can have a variety of different backends you cannot assume they are not allowed.

Depending on the backend it would be possible to leave the trimming/normalization to the backend. For example, for LDAP you could simply query the uid attribute (or whatever attribute is used for identification) to see how the user id is spelled out correctly.

For LDAP that would also solve another issue: the uid attribute in LDAP is case insensitive, i.e. upper and lower case letters make the same uid. I guess eduvpn treats the uid case sensitive and that's may be useful for some backends and not for others.

Thus, I would suggest you use some (optional) feedback from the backend to retrieve the username as used in the backend as name of identification. Otherwise, you may need additional parameter in the backend configuration to enable/disable case sensitivity (and trimming if you are at it anyway...)

I think passwords must not be trimmed or modified in any way.

**Comment by fkooman** [comment]
For now leading and trailing whitespace is stripped. That solves one immediate problem. But indeed, for LDAP it would be nice to be able to fix it in a better way as you suggest. 

This would need to be fixed here: https://github.com/eduvpn/vpn-lib-common/blob/master/src/Http/LdapAuth.php

The LDAP client that is used is this one: https://github.com/eduvpn/vpn-lib-common/blob/master/src/LdapClient.php  

Should be relatively easy to properly fix, however I can't test it as I don't have an LDAP server available...

**Comment by gvde** [comment]
Looking through the documenation for the other authentication types I think the consistent thing to do would be to add an "userIdAttribute" configuration option to ldapauth to name the identification attribute to use (e.g. "uid").

In LdapAuth.php you could then search for the user entry to extract the permissions and uid attribute.

**Comment by fkooman** [comment]
Yeah, that seems to be the best approach! Currently no search is performed though, so that should be added... But also adding a configuration option is a bit unfortunate. This could be solved together with some other LDAP work required for better AD support. Those patches are not in GH yet, but in a mail.

**Comment by fkooman** [comment]
I just put the AD changes in gist: https://gist.github.com/fkooman/7fa97788d878ac9eb1254554cb8b1eb2

**Comment by fkooman** [comment]
The challenge is now to fix all this without breaking existing deploys and not requiring a new class for LDAP :)

**Comment by fkooman** [comment]
> Looking through the documenation for the other authentication types I think the consistent thing to do would be to add an "userIdAttribute" configuration option to ldapauth to name the identification attribute to use (e.g. "uid").
> 
> In LdapAuth.php you could then search for the user entry to extract the permissions and uid attribute.

This is exactly what I did now. I "invented" the solution myself, only to realize you exactly came up with the same thing already!

Will be part of 2.2.4 release.

**Comment by fkooman** [comment]
Production release is there! All done.

**Comment by gvde** [comment]
I have updated our servers and it looks good. Tests show the correct uid in the internal databases regardless of spaces or capitalization entered in the user portal... Thanks.
