### ISSUE TITLE
approve button on iOS device needs re-order on page

### ISSUE THREAD

**Issue by efef** [eduvpn/vpn-user-portal#153]
In our new iOS app the 'approve' button is not visible directly.

![signal-2019-12-23-101703](https://user-images.githubusercontent.com/3393474/71348885-d4330d80-256d-11ea-8805-b9be412c8fbc.png)

Probably putting the 'approve' button on top?

**Comment by fkooman** [comment]
Hopefully solved by removing the "Sign Out" button on the OAuth authorize page.

https://github.com/eduvpn/vpn-user-portal/commit/ab3a3341d2e2d78a0b76d840c080cdbb7b10232c

**Comment by fkooman** [comment]
![signal-2019-12-23-134938](https://user-images.githubusercontent.com/616885/71358964-27678900-258b-11ea-82bb-3a741a3f3af3.png)
