### ISSUE TITLE
easy find blocked users

### ISSUE THREAD

**Issue by efef** [eduvpn/vpn-user-portal#168]
When a user is blocked it is quite difficult to find which user is blocked in the admin-portal when there  are many users. In particular when you don't know to search for which keyword. In my case the Dutch "Uitgeschakeld" was required to find  the blocked user.

Would suggest to put on top the number of blocked users with  a clickable link. 
Or sort the blocked users, so they are always on top or below the current table.

**Comment by fkooman** [comment]
https://todo.sr.ht/~eduvpn/server/36
