### ISSUE TITLE
connection log

### ISSUE THREAD

**Issue by gvde** [eduvpn/vpn-user-portal#170]
I like the new connection log. However, it would be more useful if it also listed the client which connected and maybe even the IP address from where it connected.

In particular the mobile clients may cause numerous connections to happen and it is kind of difficult to see which connection happened for what reason. Maybe even the connections log could be group by client/source ip on each day or similar. That way it would be even more easier to distinguish the desktop and mobile connections.

**Comment by fkooman** [comment]
> I like the new connection log. However, it would be more useful if it also listed the client which connected and maybe even the IP address from where it connected.

This information is not available. The originating client IP is explicitly not logged and also not something we want to add... I can't find a valid reason for doing this, except "nice to have". We have to avoid simply logging as much as possible, and instead focus on the absolute least necessary to operate the service. I can even see it go in the other direction: log even less...

What is currently shown is the data that is logged anyway, but deleted after 30 days, and is required to trace back abuse (if any occurs).

What _is_ planned is showing the active connections for a user in the portal.

**Comment by gvde** [comment]
Well, the client_id (e.g. org.eduvpn.app.ios) which created the certificate used is available. That would help to identify mobile and desktop connections.

**Comment by fkooman** [comment]
I guess we could modify the SQL query [here](https://github.com/eduvpn/vpn-server-api/blob/e1c5cd78f26be9e0d05edc96def00df397a16e69/src/Storage.php#L534) to also return the `client_id` and list that in a separate column, or just like the client IP addresses and data transferred as "mouse overs" over the connect/disconnect columns...

**Comment by fkooman** [comment]
Something like this, but then better looking...

![image](https://user-images.githubusercontent.com/616885/86131974-9b5c8e00-bae6-11ea-805d-2ffac3168ae4.png)

**Comment by fkooman** [comment]
Some work on this has been done in the 3.x portal, it is possible to see which application is used to connect. Furthermore the syslog component allows logging connect/disconnect events with "originating IP".

![image](https://user-images.githubusercontent.com/616885/148776664-61c90959-382f-4b6e-8cca-73af52b4e3ef.png)
