### ISSUE TITLE
well-known configuration is in violation with RFC8615 section 3

### ISSUE THREAD

**Issue by jornane** [eduvpn/vpn-user-portal#173]
eduVPN uses the well-known URL `/.well-known/vpn-user-portal` for providing apps with version information and endpoints. However, the `/.well-known` path is governed by RFC8615 which states:

> Applications that wish to mint new well-known URIs MUST register them, following the procedures in Section 5.1

The list of allocated assignments is here: https://www.iana.org/assignments/well-known-uris/

The project should change the endpoint for apps to not start with `/.well-known/`, or register an entry with IANA.

**Comment by fkooman** [comment]
I guess a global `/info.json` is better? At least it doesn't "violate" the RFC? :shrug:

**Comment by fkooman** [comment]
Maybe I can use the `/.not-so-well-known` prefix? :laughing:
