### ISSUE TITLE
Portal documentation outdated

### ISSUE THREAD

**Issue by gvde** [eduvpn/vpn-user-portal#175]
The documentation in the portal suggests to install openvpn, tunnelblick, etc. instead of the eduvpn client. It should be modified or at least the current text should be removed to keep some people from actually trying that...

**Comment by fkooman** [comment]
This is solved by installing and activating the "eduVPN" style, see https://github.com/eduvpn/documentation/blob/v2/BRANDING.md

**Comment by fkooman** [comment]
Documentation page has been completely deleted in 3.x code.
