### ISSUE TITLE
u2f support

### ISSUE THREAD

**Issue by gvde** [eduvpn/vpn-user-portal#176]
I use a yubikey for my totp generation. I would be nice if eduvpn would support u2f and I could directly use the yubikey as security key instead of copying the generated totp number like you can do with github, facebook and others.

See https://developers.yubico.com/U2F/

**Comment by fkooman** [comment]
Would be nice! But probably better FIDO2 then. The problem with it is that it is such a mess to implement with the pile of JS you need to run in the browser... not sure if there are already super simple client side libraries for implementing this without the need for "the cloud"? Do you know this?

**Comment by fkooman** [comment]
I had another look at it, I'm sure it is not going to happen in eduVPN. The standards are really horrible. I'm not sure how they could have made a worse standard, even if they tried...

See https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API and also look at the links they provide at the end of that document where they point to demo code. Are they serious?! 

Also this: https://webauthn.guide/, it reads like a bad joke 🤣 for something that is conceptually extremely simple...

I understand that it would be really nice to have FIDO2/U2F/WebAuthn support in eduVPN, but well... unless they fix the standard any make it easy to implement, without requiring JS, where you can actually understand what is going on without spending weeks digging through the standards and code examples, I am not going to spend any time on it. Sorry.
