### ISSUE TITLE
URL /vpn-user-portal/ was not found on this server.

### ISSUE THREAD

**Issue by bhagat-san** [eduvpn/vpn-user-portal#179]
URL /vpn-user-portal/ was not found on this server.

**Comment by fkooman** [comment]
If you want to install and eduVPN / Let's Connect! server, please follow the instructions here: https://github.com/eduvpn/documentation#deployment

If you are part of the educational/research community please contact us on eduvpn-support@lists.geant.org so we can schedule a call and help you get going!
