### ISSUE TITLE
connected only eduvpn application only

### ISSUE THREAD

**Issue by fadloero1010** [eduvpn/vpn-user-portal#184]
How do clients connect via the EDUVPN only application, sign that they can connect using other OpenVPN applications?

**Comment by fkooman** [comment]
I'm trying to understand what you wrote:

1. You are asking how to prevent other clients than eduVPN clients from connecting to eduVPN server?
2. You are asking how to connect to the eduVPN server with other OpenVPN clients?

**Comment by fadloero1010** [comment]
I see the status of Application Usage that uses more eduvpn through the Manual Configuration Download application as much as 98%, compared to the eduvpn application by 5%.

![Screenshot 2021-04-29 at 12 21 30 PM](https://user-images.githubusercontent.com/82032976/116502329-c6219980-a8e5-11eb-896a-32faca548d60.png)

Can it prevent clients / students from logging in outside of EDUVPN, so that the graphical usage of the EDUVPN application increases?

**Comment by fkooman** [comment]
#147

**Comment by fkooman** [comment]
implemented for eduVPN/Let's Connect! version 3, release later this year.

https://github.com/eduvpn/vpn-user-portal/commit/a6c4a3bdddbbedf27e7196c13e37029e1088ce3c
