### ISSUE TITLE
Custom names for authorized applications

### ISSUE THREAD

**Issue by csware** [eduvpn/vpn-user-portal#188]
If you have different computers all running the very same OS then you have several entries such as "eduVPN for Windows".

Now imagine you want to revoke an application for a specific device, then your only indicator is the "authorized on" column which is not very helpful.

Therefore, I request that a user can rename or add a custom comment to an authorized application to distict them.

**Comment by fkooman** [comment]
I do see the appeal of this, but we won't be implementing this.

It would only interest a very small amount of users and requires significant effort to implement in portal, apps and API and has privacy implications if users are allowed to enter their own text, or text is automatically extracted from the OS environment the apps are running on, e.g. computer name.
