### ISSUE TITLE
FOUC in Firefox on "New" page

### ISSUE THREAD

**Issue by fkooman** [eduvpn/vpn-user-portal#67]
https://bugzilla.mozilla.org/show_bug.cgi?id=712130

**Comment by sveeke** [comment]
To give an ilustration:

![image](https://user-images.githubusercontent.com/12334213/30295709-dbaf7fb0-9741-11e7-8616-88452586efe9.png)

**Comment by fkooman** [comment]
Maybe we should just not have any CSS? :-)

**Comment by fkooman** [comment]
It can be fixes by a JS one-liner, and removing the `autofocus` from the `<input>`:

```
document.addEventListener("DOMContentLoaded", function () {
    "use strict";
    document.querySelector("input#displayName").focus();
});
```

**Comment by fkooman** [comment]
It is actually a bit more involved. As this element is not available on every page, so it needs to be a bit smarter. And this is also a problem with the login page (FormAuthentication).

**Comment by sveeke** [comment]
I suggest we park this issue until it becomes more annoying or when we get questions/complaints about it from users. Until then, let's minimize the use of javascript.
