### ISSUE TITLE
Ability to completely disable 2FA as administrator

### ISSUE THREAD

**Issue by jornane** [eduvpn/vpn-user-portal#87]
The Norwegian NREN has support for 2FA for SAML logins. It can be confusing for users and helpdesk to have two different 2FA solutions, so I would like to disable 2FA support in eduVPN so that all 2FA is handled at the IdP-side.

**Comment by fkooman** [comment]
Related: https://github.com/eduvpn/vpn-server-api/issues/53

**Comment by fkooman** [comment]
Related: #60

**Comment by fkooman** [comment]
https://github.com/eduvpn/vpn-user-portal/compare/otp-disable

**Comment by fkooman** [comment]
Feature branch giving admins the option to disable TOTP and/or YubiKey OTP. The new default will be to only allow TOTP as we want to deprecate YubiKey OTP as it depends on a (proprietary) remote service.

**Comment by fkooman** [comment]
merged.
