### ISSUE TITLE
revoking an OAuth client should delete all certificates obtained using this client

### ISSUE THREAD

**Issue by fkooman** [eduvpn/vpn-user-portal#89]
currently, only the permission is revoked for obtaining new access_tokens using the refresh_tokens and the current access_token is made invalid. The VPN certificate remains valid until it expires.

It seems there is no link between the client_id and the issued certificate at the moment, so this is not possible. 

Probably have to wait for 2.0 refactor!

**Comment by rozmansi** [comment]
The Windows client does not cache the profile configuration. Therefore, it will attempt to get the profile configuration on each connect - and fail due to the invalidated access token.

The problem is a manual OpenVPN profile&cert client set-ups.

**Comment by fkooman** [comment]
sure, but even though the windows client does not work anymore, it will still technically be possible to "extract" the certificate and use it outside of the app.

This fix is not in the applications, but in the server.
